// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhYREXBm--CtAxs-YELAyzk6rT0HO2OIw',
    appId: '1:599940066361:web:3176eeb4405d487e0371e8',
    messagingSenderId: '599940066361',
    projectId: 'elmogps-production',
    authDomain: 'elmogps-production.firebaseapp.com',
    storageBucket: 'elmogps-production.firebasestorage.app',
    measurementId: 'G-CSNSXF8FCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBY7crvZ4KJPWLAY6p9nbXlTkVrbJ5H5Y',
    appId: '1:599940066361:android:52801456525de22d0371e8',
    messagingSenderId: '599940066361',
    projectId: 'elmogps-production',
    storageBucket: 'elmogps-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlX5bSwanEh8ciaR1YIeJrzRbaHGeB9lE',
    appId: '1:599940066361:ios:5e987aff5df07ef90371e8',
    messagingSenderId: '599940066361',
    projectId: 'elmogps-production',
    storageBucket: 'elmogps-production.firebasestorage.app',
    iosBundleId: 'com.example.elmogps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlX5bSwanEh8ciaR1YIeJrzRbaHGeB9lE',
    appId: '1:599940066361:ios:5e987aff5df07ef90371e8',
    messagingSenderId: '599940066361',
    projectId: 'elmogps-production',
    storageBucket: 'elmogps-production.firebasestorage.app',
    iosBundleId: 'com.example.elmogps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhYREXBm--CtAxs-YELAyzk6rT0HO2OIw',
    appId: '1:599940066361:web:8f8d706c62a535800371e8',
    messagingSenderId: '599940066361',
    projectId: 'elmogps-production',
    authDomain: 'elmogps-production.firebaseapp.com',
    storageBucket: 'elmogps-production.firebasestorage.app',
    measurementId: 'G-B4EFNEHZBM',
  );
}
